# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WisdomScanKitDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WisdomScanKitDemo
  pod 'SnapKit'

  pod 'WisdomHUD'#, '~> 0.2.2'
end
